### ISSUE TITLE
Sprite - Cauldron

### ISSUE THREAD

**Issue by Strandiel** [ProMedi24-1/HordeSurvivalGame#34]
Create the sprite for a bubbling cauldron, liquid should be white to allow for easy color changes (?)

**Comment by Mori2003** [comment]
Just a simple first concept. Logs and fire underneath the cauldron are missing (could probably also seperate these so into individual sprites). I think the dimensions should be around 64x48px, so it's like 4 Grid sizes. Also the liquid should be seperate in the final version.
![grafik](https://github.com/ProMedi24-1/HordeSurvivalGame/assets/139063007/08e8f9ba-088a-46c1-88f3-61acca1851fa)

**Comment by Mori2003** [comment]
![cauldron](https://github.com/ProMedi24-1/HordeSurvivalGame/assets/139063007/967c6dbe-b0ba-4bc5-8b44-6d68bd4c1ae6)
Would label this issue as closed. Cauldron is in the Project and has animated fire and liquid. Liquid color is easily changeable by using the `modulate` property of the Sprite. Of course it is non final, and some things may need to be tweaked.
