### ISSUE TITLE
Implementation: Bat enemy

### ISSUE THREAD

**Issue by Strandiel** [ProMedi24-1/HordeSurvivalGame#59]
Implement the bat enemy into the game, add collision circle, basic movement
Look at what we already have implemented
![BatSprite](https://github.com/ProMedi24-1/HordeSurvivalGame/assets/169077098/a62cde3e-1e47-4221-a63a-c90408ee504f)
Tutorial:
https://www.youtube.com/watch?v=9u59U-DWNJs

**Comment by Mori2003** [comment]
Implemented in #65. However we shouldn't close this, because we still need to implement the other evolutions.
